sudo: required

dist: trusty

language: node_js

node_js:
  - "7"

before_install:
  - npm install -g ethereumjs-testrpc truffle

script:
  - testrpc > /dev/null &
  - truffle test
  
notifications:
  email: false
